services:
  dolphinscheduler:
    image: apache/dolphinscheduler-standalone-server:latest
    container_name: dolphinscheduler
    hostname: dolphinscheduler
    ports:
      - "12345:12345"
    volumes:
      - ../../data_volume/dolphinscheduler-data:/tmp/dolphinscheduler
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    networks:
      - ldl-net

networks:
  ldl-net:
    external: true
    name: ldl-net

